### ISSUE TITLE
Written on Windows?

### ISSUE THREAD

**Issue by mvhirsch** [owdevel/ytdl-nfo#3]
Hi, I would really love to use this project to generate nfo files for my kodi setup.
Unfortunately I'm unable to use this library on my Fedora 34, Python 3.9.

Since sometimes `ytdl_nfo`is written with underscore, sometimes with hyphen, and (which really matters on incase-sensitive systems): sometimes it's written `ytdl_nfo` and sometimes `Ytdl_nfo`. Was this library written on a Windows OS? 'Cause I cannot import it, cause it won't find it (naming). 

After fixing this in `__main__.py` my next issue is, that I'm unable to load `get_config`. Where does this library come from?
Sorry, I'm not an experienced python developer, but eager to help!

Could you please help me, figuring out?

Greets from Austria,
Michael

**Comment by owdevel** [comment]
Hey Michael,

Sorry for the late reply. I've been developing this mainly on manjaro (arch) and ubuntu based systems with python 3.9, keeping the naming as consistent I can to the youtube-dl's project naming. As such I don't think the naming is a problem in this case.

This script has been primarily designed so far to run as a standalone script so importing it as a module is mostly untested which is why you may be running into bugs.

I've done some testing and added a getter so it should now have basic functionalities as a module. If you pip uninstall and pip install you should be able to use the following to get the formatted data.
```python3
import ytdl_nfo

ytnfo = ytdl_nfo.Ytdl_nfo('enter_path_to_json')
ytnfo.process()
nfo = ytnfo.get_nfo()
```
As I have limited time I will primarily be focusing on updating the tool for its primary use case as a standalone program, but if you need extra module functionality please let me know or submit a pull request and I'll try and fit it in. Let me know if this helps.

Kind Regards,
Owen

**Comment by mvhirsch** [comment]
Hi Owen, 

Thank you for your reply. Unfortunately, it doesnt help me. I'm not interested in using it as a library, instead I followed the instructions on readme, using manual install (git clone & pip install req.). After that, how do I actually run the program correctly? I wasn't able to figure that out (missing command line example as final step after installing requirements).

So I tried running various commands, without luck, resulting in confusion about lower-/uppercase and that missing module "get_config".

After manual install, how should I run the command correctly? Could you please write an example CLI command, after `pip install -r requirements.txt`?

That would help me a lot!
Many thanks in advance,
Michael

**Comment by pineapplemachine** [comment]
In the root directory of the cloned git repo:

```
> pip install .
> ytdl-nfo [your-file-path]
```

It looks like this step may be missing from the readme for manual install, after installing requirements.

**Comment by mvhirsch** [comment]
Awesome! Thank you!

That worked for me :-D
